from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_RELATIVE_PATH = "MANIFEST.sha256"

_GENERATED_SCHEMA_ROOTS = (
    "reference/schemas-v0.19.0",
    "src/sc_referee/resources/schemas-v0.19.0",
)
_PROMOTED_RELEASE_ARTIFACTS = ("scripts/migrate_v0_18_to_v0_19.py",)


def _generated_schema_artifacts(root: Path = ROOT) -> tuple[str, ...]:
    """Read only the release-builder's closed internal manifests, never the tree at large."""

    artifacts: set[str] = set()
    for relative_root in _GENERATED_SCHEMA_ROOTS:
        package_root = root / relative_root
        manifest = package_root / "MANIFEST.sha256"
        if not manifest.is_file():
            continue
        artifacts.add(f"{relative_root}/MANIFEST.sha256")
        for line in manifest.read_text(encoding="utf-8").splitlines():
            _digest, separator, relative = line.partition("  ")
            path = Path(relative)
            if (
                not separator
                or path.is_absolute()
                or ".." in path.parts
                or relative == "MANIFEST.sha256"
            ):
                raise RuntimeError(f"invalid generated schema artifact path: {relative!r}")
            artifacts.add(f"{relative_root}/{relative}")
    return tuple(sorted(artifacts))


# v0.19 is generated by the accepted release builder before the surrounding
# commit exists. Its own closed manifests admit exactly those generated files.
# The public migration is the one exact promoted release artifact replacing
# the candidate entry point. Arbitrary untracked working-tree files remain
# excluded because every pre-commit exception is named or internally sealed.
INTENTIONALLY_GENERATED_ARTIFACTS: tuple[str, ...] = tuple(
    sorted(set(_generated_schema_artifacts()) | set(_PROMOTED_RELEASE_ARTIFACTS))
)


def git_tree_inventory(root: Path = ROOT) -> tuple[str, ...]:
    """Return the exact file inventory committed at ``HEAD``.

    Content is read from the working tree so a regenerated manifest describes
    the proposed tracked changes, but path admission comes only from Git's
    committed tree.  Untracked and ignored working-tree files are therefore
    incapable of entering the manifest.
    """

    try:
        completed = subprocess.run(
            [
                "git",
                "-C",
                str(root),
                "ls-tree",
                "-r",
                "--full-tree",
                "--name-only",
                "-z",
                "HEAD",
            ],
            check=True,
            capture_output=True,
        )
        paths = tuple(
            item.decode("utf-8", errors="strict") for item in completed.stdout.split(b"\0") if item
        )
    except (OSError, subprocess.CalledProcessError, UnicodeDecodeError) as error:
        raise RuntimeError("unable to read the committed Git tree for the manifest") from error
    if not paths or len(paths) != len(set(paths)):
        raise RuntimeError("the committed Git tree inventory is empty or ambiguous")
    return tuple(sorted(paths))


def manifest_inventory(root: Path = ROOT) -> tuple[str, ...]:
    """Return the closed tracked-plus-explicit-generated manifest inventory."""

    relative_paths = (set(git_tree_inventory(root)) - {MANIFEST_RELATIVE_PATH}) | set(
        INTENTIONALLY_GENERATED_ARTIFACTS
    )
    for relative in relative_paths:
        path = Path(relative)
        if path.is_absolute() or ".." in path.parts or not (root / path).is_file():
            raise RuntimeError(f"manifest inventory path is unavailable: {relative}")
    return tuple(sorted(relative_paths))


def build_manifest_rows(root: Path = ROOT) -> tuple[str, ...]:
    """Hash current bytes for the exact admitted path inventory."""

    return tuple(
        f"{hashlib.sha256((root / relative).read_bytes()).hexdigest()}  {relative}"
        for relative in manifest_inventory(root)
    )


def main() -> None:
    rows = build_manifest_rows()
    (ROOT / MANIFEST_RELATIVE_PATH).write_text("\n".join(rows) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
